### ISSUE TITLE
lineView不显示和位置不更新

### ISSUE THREAD

**Issue by HouHangLei** [wwmz/WMZPageController#62]
在”淘宝滑动动态改变菜单栏“模式中，在常态模式下选中其他Menu，上划到改变高度的状态时，lineView还是在原先的Menu下面

**Comment by HouHangLei** [comment]
而且我这边首次不显示lineView，需要左右滑动或者点击Menu以后才出现。不过demo里没有这个问题。

**Comment by HouHangLei** [comment]
大佬，有临时解决办法吗？比较着急

**Comment by wwmz** [comment]
> 大佬，有临时解决办法吗？比较着急

第一个问题已修复 第二个问题没重现 有点忙 cocopod没更新 等会先直接下载代码哈

**Comment by wwmz** [comment]
你首次不显示是因为在改变高度的时候没有把line显示出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 侯航磊 ***@***.***&gt;
发送时间: 2021年11月15日 20:06
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] lineView不显示和位置不更新 (Issue #62)





 
而且我这边首次不显示lineView，需要左右滑动或者点击Menu以后才出现。不过demo里没有这个问题。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HouHangLei** [comment]
是在wEventMenuChangeHeightSet中设置Hidden为false吗？我设置了啊，和demo中写的一样。只不过我用swift写的
